on:
  push:
    branches:
    - master
name: Push Event
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - run: npm run test